const roles=[
 {kicker:'CURRENT ROLE · DTE ENERGY',title:'Data Tech Process Analyst',company:'Damage Claims Team · Apr 2026 – Present',body:'I use Python to update Databricks app interfaces and connect data from backend tables. I also build Python pipelines for SAP C4C and Smartsheet data, and use SQL for UAT and data validation.',skills:['Python','Visual Studio Code','SQL','Databricks','OData API','Smartsheet API']},
 {kicker:'DTE ENERGY',title:'Operations Analyst (Contractor)',company:'EFO Team · Aug 2025 – Apr 2026',body:'Built Power BI dashboards for leadership, used SQL to analyze operational and financial data, and led the development of a PowerApps solution that reduced manual work.',skills:['Power BI','SQL','PowerApps','Financial Reporting','Process Improvement']},
 {kicker:'DTE ENERGY',title:'Analyst Co-Op',company:'Damage Claims Team · May 2023 – Aug 2025',body:'Created SQL reports for daily claims and credit decisions, built Power BI dashboards, worked on escalated claims across several business systems, and managed large Smartsheet datasets.',skills:['SQL','Power BI','Databricks','SAP','CRM','Smartsheet','Excel']}
];

const projects=[
 {id:'scorecard',num:'01',category:['engineering'],title:'Scorecard Automation',summary:'Built an automated scorecard pipeline that pulls Smartsheet data into Databricks, uses SQL to transform and join data, and uses Python to send scheduled email reports to stakeholders.',problem:'Scorecard data needed to be pulled, prepared, and shared on a recurring basis without relying on manual updates.',build:'Connected the Smartsheet API to Databricks, used SQL to transform and join the data, and wrote Python code to send scheduled email reports.',impact:'Automated recurring scorecard data preparation and stakeholder reporting.',tools:['SQL','Python','PySpark','Smartsheet API','Databricks']},

 {id:'sap',num:'02',category:['engineering'],title:'SAP C4C Data Extraction into Databricks',summary:'Built an automated pipeline that uses Python to pull SAP C4C data through OData APIs, store it in Databricks tables, and schedule recurring data pulls for reporting and automation.',problem:'SAP C4C data needed to be available in Databricks on a recurring basis for reporting and automation.',build:'Used Python with OData APIs to pull collection-level and child-node data, load it into Databricks tables, and schedule recurring jobs.',impact:'Made SAP C4C data consistently available for downstream reporting and automation.',tools:['Python','OData API','Databricks','SAP C4C']},

 {id:'credit',num:'03',category:['analytics'],title:'Credit Allocation Project',summary:'Led the allocation of over $800K in customer credits, using SQL in Databricks and Excel to verify eligibility, validate data, and ensure accurate distribution.',problem:'A large credit allocation required careful eligibility checks and validation before distribution.',build:'Used SQL in Databricks and Excel to check eligibility, validate the data, and confirm the correct credit amounts before distribution.',impact:'Supported accurate distribution of more than $800K in credits.',tools:['SQL','Excel','Databricks']},

 {id:'reliability',num:'04',category:['engineering'],title:'Reliability Credit Validation',summary:'Used SQL in Databricks to identify false outage records that were being picked up for customer credits, preventing over $10K in inaccurate reliability credits from being approved.',problem:'The credit processing UI could not identify false outage records in the database, which meant some customers could incorrectly qualify for reliability credits.',build:'Wrote SQL queries in Databricks to identify false outage records and exclude them from the credit approval process.',impact:'Prevented over $10K in inaccurate reliability credits from being approved.',tools:['SQL','Databricks','Data Validation']},

 {id:'claims',num:'05',category:['analytics'],title:'Financial & Escalation Claims Dashboards',summary:'Built Power BI dashboards using SQL, Databricks, and Smartsheet data to track multi-million-dollar claims and escalations.',problem:'Leadership needed one place to track financial claims and escalated cases across multiple data sources.',build:'Combined SQL, Databricks, and Smartsheet data in Power BI dashboards for claims and escalation tracking.',impact:'Improved visibility into multi-million-dollar claims and open escalations.',tools:['Power BI','SQL','Smartsheet','Databricks']},

 {id:'ssr',num:'06',category:['analytics'],title:'SSR Recommendation Project',summary:'Analyzed service center data using SQL in Databricks to recommend engineer allocation and presented the findings to the director for resource planning.',problem:'Leadership needed data to help decide where engineering resources should be allocated.',build:'Analyzed service center data with SQL in Databricks and turned the results into an engineer allocation recommendation.',impact:'Presented the recommendation to leadership for resource planning.',tools:['SQL','Databricks','Analysis']}
];

const roleDetail=document.getElementById('roleDetail');
function renderRole(i){const r=roles[i];roleDetail.innerHTML=`<div class="role-kicker">${r.kicker}</div><h3>${r.title}</h3><h4>${r.company}</h4><p>${r.body}</p><div class="chips">${r.skills.map(x=>`<span>${x}</span>`).join('')}</div>`}
renderRole(0);
document.querySelectorAll('.role-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderRole(+btn.dataset.role)}));

const grid=document.getElementById('projectGrid');
function renderProjects(filter='all'){const items=projects.filter(p=>filter==='all'||p.category.includes(filter));grid.innerHTML=items.map(p=>`<article class="project-card" data-id="${p.id}"><span class="project-num">${p.num}</span><span class="project-open">↗</span><h3>${p.title}</h3><p>${p.summary}</p><div class="chips">${p.tools.slice(0,3).map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('.project-card').forEach(c=>c.addEventListener('click',()=>openProject(c.dataset.id)))}
renderProjects();
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderProjects(btn.dataset.filter)}));

const modal=document.getElementById('projectModal');
const modalContent=document.getElementById('modalContent');
function openProject(id){const p=projects.find(x=>x.id===id);modalContent.innerHTML=`<div class="modal-body"><div class="modal-num">PROJECT ${p.num}</div><h3>${p.title}</h3><p>${p.summary}</p><div class="modal-grid"><div class="modal-box"><small>Why</small><strong>${p.problem}</strong></div><div class="modal-box"><small>What I did</small><strong>${p.build}</strong></div><div class="modal-box"><small>Result</small><strong>${p.impact}</strong></div><div class="modal-box"><small>Tools</small><strong>${p.tools.join(' · ')}</strong></div></div></div>`;modal.showModal()}
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
document.getElementById('year').textContent=new Date().getFullYear();
