const roles=[
 {kicker:'CURRENT ROLE · DTE ENERGY',title:'Data Tech Process Analyst',company:'DTE Energy · Detroit, Michigan',body:'Build end-to-end data pipelines, automated workflows, reporting solutions, and operational analytics. My work connects business processes with enterprise data using Python, SQL, Databricks, Power BI, SAP, Smartsheet, PowerApps, and related tools.',skills:['Python','SQL','Databricks','Power BI','ETL','APIs','Automation']},
 {kicker:'DTE ENERGY',title:'Operations Analyst',company:'Damage Claims & Regulatory Affairs',body:'Supported claims operations through reporting, scorecards, process analysis, workflow improvement, data quality checks, and automation. Partnered with business teams to turn recurring operational tasks into more consistent, measurable processes.',skills:['Operations Analytics','Reporting','Process Improvement','Data Validation','Stakeholder Support']},
 {kicker:'DTE ENERGY',title:'Damage Claims & Regulatory Affairs Co-op',company:'DTE Energy',body:'Worked within damage claims and regulatory operations, building a foundation in claims processes, data analysis, reporting, and cross-functional support that later expanded into larger automation and analytics initiatives.',skills:['Claims Operations','Excel','Analytics','Reporting','Process Support']},
 {kicker:'DTE ENERGY',title:'Customer Excellence Team Co-op',company:'DTE Energy',body:'Supported customer-focused operational work and learned how enterprise teams use data, process controls, and cross-functional coordination to improve service delivery and business outcomes.',skills:['Customer Operations','Data Support','Collaboration','Process Execution']}
];

const projects=[
 {id:'credit',num:'01',category:['analytics','automation'],title:'Credit Allocation Project',summary:'Led an initiative distributing more than $800K in credits using SQL in Databricks and Excel-based validation to support accurate disbursement.',problem:'A high-value credit process needed reliable validation and accurate allocation across a large claim population.',build:'Designed SQL queries and validation logic in Databricks, paired with Excel checks, to identify eligible records, verify output, and support accurate credit allocation.',impact:'Supported distribution of more than $800K in credits while improving confidence in the underlying data and allocation process.',tools:['SQL','Databricks','Excel','Data Validation']},
 {id:'claims',num:'02',category:['analytics','automation'],title:'Financial & Escalation Claims Dashboards',summary:'Built dashboards that consolidated multi-million-dollar claims data and tracked escalated cases through completion.',problem:'Leadership needed clearer visibility into financial claims performance and unresolved escalations across multiple data sources.',build:'Combined Power BI, SQL, Databricks, and Smartsheet data into reporting views for financial tracking and escalation status.',impact:'Improved financial visibility, accountability, and follow-through on escalated claims.',tools:['Power BI','SQL','Databricks','Smartsheet']},
 {id:'pipeline',num:'03',category:['engineering','automation'],title:'Smartsheet → Databricks Data Pipeline',summary:'Built an end-to-end pipeline that moves Smartsheet data into Databricks, validates it, transforms it, and publishes analytics-ready tables.',problem:'Operational data living in Smartsheet needed a repeatable path into Databricks for analytics and scorecard reporting.',build:'Used the Smartsheet API with Python, SQL transformations, temporary views, multi-source joins, Databricks catalog tables, and scheduled jobs.',impact:'Reduced manual data movement and created a repeatable source for downstream reporting and analytics.',tools:['Python','Smartsheet API','SQL','Databricks Jobs','ETL']},
 {id:'sap',num:'04',category:['engineering','automation'],title:'SAP C4C Data Extraction',summary:'Automated recurring extraction of SAP C4C OData collections and child-node data into Databricks.',problem:'Analytics required recurring access to SAP C4C data that was distributed across parent collections and related child nodes.',build:'Created Python extraction logic for OData endpoints, normalized the returned data, and scheduled recurring ingestion into Databricks.',impact:'Made SAP data more accessible for repeatable analytics without recurring manual exports.',tools:['Python','SAP C4C','OData API','Databricks','Scheduling']},
 {id:'geo',num:'05',category:['engineering','analytics'],title:'Closest-Job Geospatial Matching',summary:'Matched jobs by latitude and longitude to identify the nearest related job within 500 meters and connect it to line-cost data.',problem:'A baseline invoice process needed a reliable way to find geographically related jobs and reference associated cost information.',build:'Joined job coordinates, calculated nearest-job relationships within a 500-meter threshold, and connected matched jobs to line-cost tables.',impact:'Created a data foundation for more automated baseline invoice analysis.',tools:['SQL','Geospatial Logic','Databricks','Data Matching']},
 {id:'huddle',num:'06',category:['automation'],title:'Digitizing Huddle Information',summary:'Built a PowerApps application that centralized huddle tracking, standardized pre-huddle input, and added an integrated timer and review workflow.',problem:'Huddle information was maintained in manual tracking sheets, making preparation and consistency harder across teams.',build:'Created a Microsoft PowerApps experience for structured data entry, standardized review steps, and timing within the meeting workflow.',impact:'Streamlined preparation and created a more consistent huddle process.',tools:['PowerApps','Workflow Design','Process Improvement']},
 {id:'eligibility',num:'07',category:['automation','analytics'],title:'Daily Credit Eligibility Automation',summary:'Automated eligibility checks across roughly 10,000 claims per day to reduce manual review and improve consistency.',problem:'High-volume claims required recurring eligibility review that was time-consuming to perform manually.',build:'Developed data logic to evaluate claim populations against credit criteria on a recurring basis and surface eligible records.',impact:'Scaled a repetitive review process across approximately 10,000 daily claims.',tools:['SQL','Databricks','Automation','Data Quality']},
 {id:'ssr',num:'08',category:['analytics'],title:'SSR Recommendation Project',summary:'Analyzed service-center data in SQL to recommend engineer allocation and presented the findings to a director for resource planning.',problem:'Leadership needed a data-driven view of where engineering resources could be allocated most effectively.',build:'Analyzed service-center activity in Databricks using SQL, compared workload patterns, and translated the findings into a resource recommendation.',impact:'Delivered an actionable recommendation for engineer allocation and planning.',tools:['SQL','Databricks','Operational Analysis','Presentation']}
];

const roleDetail=document.getElementById('roleDetail');
function renderRole(i){const r=roles[i];roleDetail.innerHTML=`<div class="role-kicker">${r.kicker}</div><h3>${r.title}</h3><h4>${r.company}</h4><p>${r.body}</p><div class="chips">${r.skills.map(x=>`<span>${x}</span>`).join('')}</div>`}
renderRole(0);
document.querySelectorAll('.role-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderRole(+btn.dataset.role)}));

const grid=document.getElementById('projectGrid');
function renderProjects(filter='all'){const items=projects.filter(p=>filter==='all'||p.category.includes(filter));grid.innerHTML=items.map(p=>`<article class="project-card" data-id="${p.id}"><span class="project-num">${p.num}</span><span class="project-open">↗</span><h3>${p.title}</h3><p>${p.summary}</p><div class="chips">${p.tools.slice(0,3).map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('.project-card').forEach(c=>c.addEventListener('click',()=>openProject(c.dataset.id)))}
renderProjects();
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderProjects(btn.dataset.filter)}));

const modal=document.getElementById('projectModal');
const modalContent=document.getElementById('modalContent');
function openProject(id){const p=projects.find(x=>x.id===id);modalContent.innerHTML=`<div class="modal-body"><div class="modal-num">PROJECT ${p.num}</div><h3>${p.title}</h3><p>${p.summary}</p><div class="modal-grid"><div class="modal-box"><small>Problem</small><strong>${p.problem}</strong></div><div class="modal-box"><small>What I built</small><strong>${p.build}</strong></div><div class="modal-box"><small>Impact</small><strong>${p.impact}</strong></div><div class="modal-box"><small>Tools</small><strong>${p.tools.join(' · ')}</strong></div></div></div>`;modal.showModal()}
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
document.getElementById('year').textContent=new Date().getFullYear();
